Added checker
The-Forbidden-Trove/tft-poe-account-link pull request #2
Opened 2022-01-12 20:58 UTC by MusaviTFT

Banned account checker

2022-01-14 19:56 UTC, Jzir requested changes

2022-01-14 19:56 UTC, Jzir commented on database.js
> +      return poeAcc;
This is only gonna return it from the internal function here, checkBannedAccount will return nothing, and `request` isn't awaited.

2022-01-14 19:56 UTC, Jzir commented on database.js
> +  checkBannedAccount(poeAccountName);
You're not doing anything with this call? We should be rejecting the link silently if theyre banned - do the same as I do if they're blacklisted as per here https://github.com/The-Forbidden-Trove/tft-poe-account-link/blob/main/oauthCalls.js#L45

2022-01-15 20:03 UTC, MusaviTFT commented
Made requested changes,

2022-01-16 14:07 UTC, merged